// src/styles/tokens.ts — generated by Design Agent, consumed by all (Section 3.2)
export const tokens = {
  // Background layers (3 minimum, for depth)
  bg: {
    base:    'var(--bg-base)',      // Primary surface
    subtle:  'var(--bg-subtle)',    // Lifted cards, sections
    overlay: 'var(--bg-overlay)',   // Modals, tooltips
  },
  // Foreground
  fg: {
    primary:   'var(--fg-primary)',
    secondary: 'var(--fg-secondary)',
    muted:     'var(--fg-muted)',
  },
  // Brand
  brand: {
    accent:  'var(--brand-accent)',   // One bold color — used sparingly
    glow:    'var(--brand-glow)',     // Optional: light leak / halo
  },
  // Semantic
  semantic: {
    success: 'var(--success)',
    error:   'var(--error)',
  },
}

// Framer motion standard curves and durations (Section 3.5)
export const motionConfig = {
  curves: {
    entrance: [0.16, 1, 0.3, 1], // ease-out custom cubic-bezier
    transition: [0.65, 0, 0.35, 1], // ease-in-out
    spring: { type: 'spring', stiffness: 100, damping: 15 },
  },
  duration: {
    entrance: 0.6,
    micro: 0.2,
    page: 0.4,
  }
}
